from elasticsearch import Elasticsearch

"""
    辅助工具，check_data检查共有多少条数据，delete_all_data删除index_name下的所有数据
"""


def check_data():
    # Password for the 'elastic' user generated by Elasticsearch
    ELASTIC_PASSWORD = ""
    # Create the client instance
    client = Elasticsearch(
        " ",
        basic_auth=(" ", " ")
    )
    # Define the index name
    index_name = "change_test"

    # 查询所有数据
    res = client.search(index=index_name, body={"query": {"match_all": {}}, "size": 10000})  # 设置size为10000，获取所有数据

    # 打印文档总数
    total_count = res['hits']['total']['value']
    print(f"Total number of documents: {total_count}")

    # # 打印查询结果
    # for hit in res['hits']['hits']:
    #     print(hit["_source"])


def delete_all_data():
    # Password for the 'elastic' user generated by Elasticsearch
    ELASTIC_PASSWORD = " "
    # Create the client instance
    client = Elasticsearch(
        " ",
        basic_auth=(" ", " ")
    )
    # Define the index name
    index_name = " "

    # 使用delete_by_query API删除所有文档
    res = client.delete_by_query(index=index_name, body={"query": {"match_all": {}}})
    client.indices.delete(index=index_name)
    # 打印删除操作的结果
    if res["total"] > 0:
        print(f"Deleted {res['total']} documents from index {index_name}")
    else:
        print("No documents to delete")


if __name__ == '__main__':
    delete_all_data()
